name: json
version: 0.11.0-dev
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  charcode: ^1.1.1
  meta: ^1.1.0
  json_annotation: any

dev_dependencies:
  build_runner: ^0.8.0
  json_serializable: any
  test: ^0.12.0

dependency_overrides:
  json_annotation:
    path: ../json_annotation
  json_serializable:
    path: ../json_serializable
